[package]
name = "kvmtest"
version = "0.0.1"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]

[dependencies]
kvmtest_macro = { path = "kvmtest_macro" }
kvmtest_types = { path = "kvmtest_types" }
kvm = { git = "https://github.com/gz/kvm.git" }
x86 = "0.19"
mmap = "0.1.1"
log = "0.*"