[package]

name = "x86"
version = "0.4.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]

description = "Library to program x86 (amd64) hardware. Contains x86 specific data structure descriptions, data-tables, as well as convenience function to call assembly instructions typically not exposed in higher level languages."

homepage = "https://github.com/gz/rust-x86"
repository = "https://github.com/gz/rust-x86"
documentation = "http://gz.github.io/rust-x86/x86/"
readme = "README.md"
keywords = ["ia32", "os", "amd64", "x86", "x86-64"]
license = "MIT"

build = "build.rs"

[build-dependencies.phf_codegen]
phf_codegen = "0.7.5"

[build-dependencies.serde_json]
serde_json = "0.6.0"

[build-dependencies.csv]
csv = "0.14.3"

[dependencies]
bitflags = "0.1.0"
raw-cpuid = "1.*"

[dependencies.phf]
git = "https://github.com/sfackler/rust-phf.git"
features = ["core"]
