[package]

name = "x86"
version = "0.0.8"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]

description = "Library to program x86 (amd64) hardware. Contains x86 specific data structure descriptions, as well as convenience function to call assembly instructions typically not exposed in higher level languages."
repository = "https://github.com/gz/rust-x86"

readme = "README.md"
keywords = ["ia32", "os", "amd64", "x86"]
license = "WTFPL"

[dependencies]
bitflags = "0.1.0"
