[package]

name = "x86"
version = "0.0.2"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]

description = "Library to use x86 (amd64) specific functionality and registers."
repository = "https://github.com/gz/rust-x86"

readme = "README.md"
keywords = ["ia32", "os", "amd64", "x86"]
license = "WTFPL"
