[package]
name = "test-macros"
version = "0.0.1"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]

[dependencies]
quote = "0.3.*"

[dependencies.syn]
version = "0.11.*"
features = ["full"]

[lib]
proc-macro = true
