[package]
name = "test-macros"
version = "0.0.1"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]

[dependencies]
quote = "0.3.*"
test = { path = "../test_harness" }

[dependencies.syn]
version = "0.*"
features = ["full", "fold"]

[lib]
proc-macro = true
